import { onRequest } from "firebase-functions/v2/https";
import { Resvg } from "@resvg/resvg-js";
import SquanLib from "../squanlib.js";
import { renderSquare1SVG, renderSquare1LayerSVG } from "../scripts/drawScrambleCore.js";
import { resolveSettings } from "../scripts/apiConfig.js";

const squanLib = new SquanLib();

const PLACEHOLDER_HEX = "011233455677|998bbaddcffe";
const INVALID_MSG = "Invalid position. Double check your scramble!";

// strip matching outer quotes generated by spreadsheets
function stripWrappingQuotes(raw) {
  const str = String(raw).trim();
  if (str.length >= 2) {
    const first = str[0], last = str[str.length - 1];
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return str.slice(1, -1);
    }
  }
  return raw;
}

function inputToHex(input, mode) {
  if (mode === "hex") return input;
  if (mode === "inverse") {
    const { tlHex, blHex } = squanLib.algToHex(squanLib.invertScramble(input));
    return `${tlHex}|${blHex}`;
  }
  const { tlHex, blHex } = squanLib.algToHex(input);
  return `${tlHex}|${blHex}`;
}

// Mirrors the browser's validateSquare1Hex() — guarantees the state is a
// legal Square-1 position (no lone corners in any half-layer), otherwise the
// position can't be rendered as a real cube.
function validatePosition(hex) {
  const clean = String(hex).replace(/[|/]/, "");
  if (clean.length !== 24) throw new Error("Hex must be 24 data characters.");
  const hasLoneCorner = (halfLayer) => {
    for (const c of ["1", "3", "5", "7", "9", "b", "d", "f"]) {
      if (halfLayer.split(c).length % 2 !== 1) return true;
    }
    return false;
  };
  if (hasLoneCorner(clean.slice(0, 6)) ||
      hasLoneCorner(clean.slice(6, 12)) ||
      hasLoneCorner(clean.slice(12, 18)) ||
      hasLoneCorner(clean.slice(18, 24))) {
    throw new Error(INVALID_MSG);
  }
}

// Ports the DOM-based layer combiner from index.html's deeplink script to
// plain string ops, since Cloud Functions has no DOM.
function combineLayers(html, sc, gap, isVert) {
  const svgs = html.match(/<svg\b[^>]*>[\s\S]*?<\/svg>/g) || [];
  if (svgs.length < 2) throw new Error("Expected two <svg> layers.");
  const [svg0, svg1] = svgs;
  const getAttr = (tag, name) => tag.match(new RegExp(`${name}="([^"]*)"`))?.[1];
  const getInner = (tag) => tag.replace(/^<svg\b[^>]*>/, "").replace(/<\/svg>$/, "");

  const [vbX, vbY, vbW, vbH] = getAttr(svg0, "viewBox").split(" ").map(Number);
  const padT = -vbY, padO = -vbX;
  const margin = sc * (0.44 * (2 + gap / 100) - 1);
  const g0shift = `translate(${padO},${padT})`;
  const g1shift = isVert
    ? `translate(${padO},${padT + sc + margin})`
    : `translate(${padO + sc + margin},${padT})`;
  const totalW = isVert ? vbW : padO + sc + margin + sc + padO;
  const totalH = isVert ? padT + sc + margin + sc + padO : vbH;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${totalW}" height="${totalH}" viewBox="0 0 ${totalW} ${totalH}">` +
    `<g transform="${g0shift}">${getInner(svg0)}</g>` +
    `<g transform="${g1shift}">${getInner(svg1)}</g></svg>`;
}

// Take the first non-empty line of a multi-line input. Google Sheets passes a
// whole cell (often several scrambles, one per line); the backend should only
// render the first line instead of requiring the caller to SPLIT/index it.
function firstLine(input) {
  const lines = String(input).split(/\r?\n/);
  for (const line of lines) {
    if (line.trim() !== '') return line.trim();
  }
  return '';
}

export const drawApi = onRequest({ cors: true }, async (req, res) => {
  try {
    const q = { ...req.query };
    if (q.input != null) q.input = stripWrappingQuotes(q.input);
    // No `input` param at all defaults to `input=0`.
    if (q.input == null) q.input = "0";
    const isEmpty = String(q.input).trim() === "";

    // Empty input renders the gray placeholder cube (matches the browser),
    // never an error.
    if (isEmpty) {
      // drop color params so the placeholder is fully muted
      const { cp, c, pc, pf, scheme, ...designOnly } = q;
      const s = resolveSettings({ ...designOnly, input: PLACEHOLDER_HEX, mode: "hex" });
      const baseOptions = {
        styleIndex: s.styleIndex,
        showSideColors: s.showSideColors,
        styleSettings: s.styleSettings,
        colorScheme: s.colorScheme,
        piecesColors: s.piecesColors,
        size: s.size,
        ringDistance: s.ringDistance,
        isVertical: s.isVertical,
        showSlice: s.showSlice,
        exportPad: s.exportPad,
      };
      let svg;
      if (s.layer !== "both") {
        svg = renderSquare1LayerSVG(PLACEHOLDER_HEX, {
          ...baseOptions,
          muted: true,
          layer: s.layer === "top" ? "top" : "bottom",
        });
      } else {
        const html = renderSquare1SVG(PLACEHOLDER_HEX, { ...baseOptions, muted: true });
        const sc = Math.round(s.size * (220 / 400));
        svg = combineLayers(html, sc, s.ringDistance, s.isVertical);
      }
      if (s.fmt === "svg") {
        res.set("Content-Type", "image/svg+xml");
        res.set("Cache-Control", "public, max-age=3600");
        res.send(svg);
        return;
      }
      const png = new Resvg(svg, { fitTo: { mode: "original" } }).render().asPng();
      res.set("Content-Type", "image/png");
      res.set("Cache-Control", "public, max-age=3600");
      res.send(png);
      return;
    }

    // Shared parameter resolution (presets + defaults + style settings).
    const s = resolveSettings(q);
    // Only the first non-empty line of input is used (multi-line cells).
    s.input = firstLine(s.input);

    let hex;
    try {
      hex = inputToHex(s.input, s.mode);
      validatePosition(hex);
    } catch (err) {
      if (err.message === INVALID_MSG) {
        res.set("Content-Type", "text/plain");
        res.status(400).send(INVALID_MSG);
        return;
      }
      throw err;
    }

    const baseOptions = {
      styleIndex: s.styleIndex,
      showSideColors: s.showSideColors,
      styleSettings: s.styleSettings,
      colorScheme: s.colorScheme,
      piecesColors: s.piecesColors,
      size: s.size,
      ringDistance: s.ringDistance,
      isVertical: s.isVertical,
      showSlice: s.showSlice,
      exportPad: s.exportPad,
    };

    let svg;
    if (s.layer !== "both") {
      svg = renderSquare1LayerSVG(hex, {
        ...baseOptions,
        layer: s.layer === "top" ? "top" : "bottom",
      });
    } else {
      const html = renderSquare1SVG(hex, baseOptions);
      const sc = Math.round(s.size * (220 / 400));
      svg = combineLayers(html, sc, s.ringDistance, s.isVertical);
    }

    const fmt = s.fmt;
    if (fmt === "svg") {
      res.set("Content-Type", "image/svg+xml");
      res.set("Cache-Control", "public, max-age=3600");
      res.send(svg);
      return;
    }

    const png = new Resvg(svg, { fitTo: { mode: "original" } }).render().asPng();
    res.set("Content-Type", "image/png");
    res.set("Cache-Control", "public, max-age=3600"); // Sheets refetches on every recalc
    res.send(png);
  } catch (err) {
    console.error("drawApi error:", err);
    res.status(400).send(String(err.message || err));
  }
});
